//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.5472 版自动生成。
// 
namespace Comm.WRRFQueryKc {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RFQueryKcSoap", Namespace="http://tempuri.org/")]
    public partial class RFQueryKc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public RFQueryKc() {
            this.Url = "http://172.16.134.126/RFQueryKc.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryKc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryKc(string BarCode, string OrgCode, string UserCode, string PassWord, ref string Packet) {
            object[] results = this.Invoke("QueryKc", new object[] {
                        BarCode,
                        OrgCode,
                        UserCode,
                        PassWord,
                        Packet});
            Packet = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginQueryKc(string BarCode, string OrgCode, string UserCode, string PassWord, string Packet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("QueryKc", new object[] {
                        BarCode,
                        OrgCode,
                        UserCode,
                        PassWord,
                        Packet}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndQueryKc(System.IAsyncResult asyncResult, out string Packet) {
            object[] results = this.EndInvoke(asyncResult);
            Packet = ((string)(results[1]));
            return ((string)(results[0]));
        }
    }
}
